name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update contribution grid
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Checkout repository
        uses: actions/checkout@v2

      # Snake Animation
      - name: Generate snake
        uses: Platane/snk@main
        with:
          github_user_name: elkhailihamza
          entryPoint: 'dist/github-contribution-grid-snake2.svg'
          args: '--snake-color red'

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-contribution-grid-snake2.svg
          git commit -m "Update snake game"
          git push

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
